# Generated by Django 5.1 on 2024-08-17 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip', models.CharField(max_length=15)),
                ('alert_on', models.IntegerField(max_length=6)),
                ('prev', models.IntegerField(max_length=6)),
                ('today', models.IntegerField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
