# Generated by Django 5.1 on 2024-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='prev',
        ),
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
