# Generated by Django 5.1 on 2024-08-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_alert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='scrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrip_alert', to='core.scrip'),
        ),
    ]
