# Generated by Django 5.1 on 2024-09-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='alert_on',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='close',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='open',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='today',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='volume',
        ),
        migrations.CreateModel(
            name='WatchlistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(max_length=12)),
                ('alert_on', models.IntegerField(max_length=6)),
                ('open', models.CharField(max_length=12)),
                ('close', models.CharField(max_length=12)),
                ('volume', models.CharField(max_length=50)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistdata', to='core.watchlist')),
            ],
        ),
    ]
