# Generated by Django 5.1 on 2024-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_watchlist_alert_on_remove_watchlist_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistdata',
            name='max',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlistdata',
            name='min',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
