# Generated by Django 5.1 on 2024-09-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_watchlistdata_max_watchlistdata_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistdata',
            name='alert_on',
        ),
    ]
